config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Resources sets up gets for all of posts paths nests comments on posts
  resources :posts do
    resources :comments
  end
  # Sets home/root or '/' path to '/posts'
  root "posts#index"

  get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  # if post gets deleted comments too get smashed into nothing with dependent
  has_many :comments, dependent: :destroy
  #Classic validations with title min 5chars
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # rescue_from ActiveRecord::RecordNotFound, :with => :not_found
  # rescue_from ActionController::RoutingError, :with => :not_found
  protect_from_forgery with: :exception


  def not_found
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Uses devise to check if user is signed in unless they're on posts show/index pages
  before_action :authenticate_user!, except: [:index, :show]

  def index
    # Orders all posts from newest to oldest created
    @posts = Post.all.order('created_at DESC')
  end

  def new
    # Keeps the new post info; for rendering post if errors check create method
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      # Redirects to 'post/:id' based on saved post_id
      redirect_to @post
    else
      # Renders new post into form if !save
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

def update
  @post = Post.find(params[:id])
  if @post.update(params[:post].permit(:title, :body))
    redirect_to @post
  else
    render 'edit'
  end
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy

  redirect_to root_path
end

  private
  # Rails4 strong params, need to define which params to allow
    # Is this a security feature, google it Sean...
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>

  <% if user_signed_in? %>
    <!-- what is going on here as the second param [comment.post, comment]? Google it Sean!  -->
    <p><%= link_to 'Delete', [comment.post, comment],
                    method: :delete,
                    class: "button",
                    data: {confirm: 'Are you sure?' } %>
    </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name%><br>
    <%= f.text_field :name%>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Oxygen:400,700,300' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'logo.png' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="sidebar">
    <div id="logo">
      <!-- Sets up link to root_path set up in routes.rb sets link on img-->
      <%= link_to image_tag('logo.svg'), root_path %>
      <!-- Another way to write this...
      <%= link_to root_path do %>
        <%= image_tag "logo.svg" %>
      <% end %> -->
    </div>

    <ul>
      <li class="category">Website</li>
      <li><%= link_to "Blog", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>

    <ul>
      <li class="category">Social</li>
      <li><a target="_blank" href="https://twitter.com/SeanMNorton">Twitter</a></li>
      <li><a target="_blank" href="https://www.instagram.com/the_sean_norton">Instagram</a></li>
      <li><a target="_blank" href="https://github.com/SeanMNorton/">Github</a></li>
      <li><a target="_blank" href="mailto:Norton.Sean.M@gmail.com">Email</a></li>
    </ul>
    <% if !user_signed_in? %>
    <p class="sign_in"><%= link_to('Admin Login', new_user_session_path)  %></p>
    <% end %>
  </div>

  <div id="main_content">
    <div id="header">
      <% if current_page?(root_path) %>
        <p>All Posts</p>
      <% elsif current_page?(about_path) %>
        <p>About</p>
      <% else %>
        <%= link_to "Back to All Posts", root_path %>
      <% end %>

      <% if user_signed_in? %>
        <div class="buttons">
          <button class="button"><%= link_to "New Post", new_post_path %></button>
          <button class="button"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></button>

        </div>
      <% end %>
    </div>
<!-- Tells devise where to throw messages devise magic! -->
    <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: 'alert') %>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "logo.svg" %>
	</div>

	<div id="content">
		<h1>Hi, I'm Sean Norton</h1>
		<p>This is a pretty cool blog, I followed <a href="http://twitter.com/mackenziechild">@MackenzieChild</a>'s tutorial to help me learn Rails. </p>
		<p>This week I built a blog in Rails 4. So far Rails is amazing and allows me to do all sorts of things in a more timley fashion.</p>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<!-- Checks if and errors occur on this post -->
<% if @post.errors.any? %>
  <div id="errors">
  <!-- Pluralize will make a word plurl if number provided is above one -->
    <h2><%= pluralize(@post.errors.count, 'screw up') %> prevented this post from saving</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%>
    </ul>
  </div>
<%end%>

<!-- The meat of the form starts here the rails way -->
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%=f.label :body%><br>
    <%=f.text_area :body%>
  </p>
  <p>
    <%=f.submit%>
  </p>
<%end%>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Posts</h1>
<!-- Rails way to create a form Google this too maybe give railsy talk  -->
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

<div class="post_wrapper">
  <!-- Creates href on post.title and takes you to that posts page post/:id -->
  <h2 class="title"> <%= link_to post.title, post %> </h2>
  <!-- Another cool date method, turns date to readable string. -->
  <p class="date"> <%= post.created_at.strftime("%B, %d, %Y") %> </p>
</div>

<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Posts</h1>
<!-- Rails way to create a form Google this too maybe give railsy talk  -->
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title"> <%=  @post.title %> </h1>

  <p class="date">
    <!-- Dope ass method that figures the distance in time and puts it to words  -->
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
    <% if user_signed_in? %>
      | <%= link_to 'Edit', edit_post_path(@post) %>
      | <%= link_to 'Delete', post_path(@post), method: :delete, data: {
        confirm: 'Are you sure?' } %>
    <% end %>
  </p>

  <p class="body"> <%= raw @post.body %> </p>

  <div id="comments">
    <h2><%= pluralize(@post.comments.count, 'Comment') %></h2>
    <%= render @post.comments %>

    <h3>Add a comment:</h3>
    <%= render 'comments/form' %>
  </div>
</div>